#!/usr/bin/env -S uv run -q -s
# /// script
# requires-python = "==3.11.10"
# dependencies = ["python-xlib"]
# ///

from Xlib import X, display
from Xlib.ext import screensaver


def get_x_idletime():
    try:
        dpy = display.Display()

        if not dpy.has_extension("MIT-SCREEN-SAVER"):
            raise RuntimeError("Screen Saver extension not supported")

        root_window = dpy.screen().root
        info = screensaver.query_info(root_window)

        idle_time = info.idle

        dpy.close()

        return idle_time

    except Exception as e:
        print(f"Error while getting idle time: {e}")
        return None


if __name__ == "__main__":
    idle_time = get_x_idletime()
    if idle_time is not None:
        print(f"{idle_time}")
    else:
        print("Failed to get idle time")
