#!/usr/bin/env python3
import sys
from os.path import expanduser
from pathlib import Path

from jetbrainslib import activate, comment, remove, status


def main():
    def print_help():
        print('Usage: jetbrains-ui-scale-fix [add|com|rem|show]')

    no_args = len(sys.argv) <= 1
    arg = 'show' if no_args else sys.argv[1]
    args = {'add': activate, 'com': comment, 'rem': remove, 'show': None}
    fun = args.get(arg, None)

    folders = ['~/.config/JetBrains/', '~/.config/Google']
    paths = [Path(expanduser(folder)) for folder in folders]
    print(f'Working on folders {[str(p) for p in paths]}\n')

    for g in [p for path in paths for p in path.rglob('*.vmoptions')]:
        text = g.read_text()
        if fun is not None:
            text = fun(text)
            g.write_text(text)

        print(f'{status(text)}  {g}')

    if no_args:
        print()
        print_help()
    print('\ndone.')


if __name__ == '__main__':
    main()
