#!/usr/bin/env python3
import argparse
import os
import shutil
import sys

parser = argparse.ArgumentParser(description='Open a new terminal window')
parser.add_argument('--verbose', '-v', action='store_true', help='Print the command used to open the terminal')
args = parser.parse_args()

cwd = os.getcwd()

if sys.platform == 'darwin':
    cmd = f"""osascript -e 'tell app "Terminal"
           do script "cd {cwd}"
           activate
       end tell'"""
    if args.verbose:
        print(cmd)
    os.system(cmd)
else:
    # Try terminal emulators in order of preference
    terminals = [
        ('ptyxis', ['ptyxis', '--new-window', f'--working-directory={cwd}']),
        ('gnome-terminal', ['gnome-terminal', f'--working-directory={cwd}']),
        ('konsole', ['konsole', f'--workdir={cwd}']),
        ('xfce4-terminal', ['xfce4-terminal', f'--working-directory={cwd}']),
        ('kitty', ['kitty', '--directory', cwd]),
        ('alacritty', ['alacritty', '--working-directory', cwd]),
        ('exo-open', ['exo-open', '--launch', 'TerminalEmulator']),
    ]

    for name, cmd in terminals:
        if shutil.which(name):
            if args.verbose:
                print(' '.join(cmd))
            os.execvp(cmd[0], cmd)
            break
    else:
        print("No supported terminal emulator found", file=sys.stderr)
        sys.exit(1)
