#!/usr/bin/env python3
import os
import sys

if sys.platform == 'darwin':
    os.system(f"""osascript -e 'tell app "Terminal"
           do script "cd {os.getcwd()}"
           activate
       end tell'""")
else:
    os.system(f"exo-open --launch TerminalEmulator")
