#!/usr/bin/env python3

def uv_available() -> bool:
    pass


def fail(msg: str):
    print(msg)


def main():
    if not uv_available():
        return fail('todo')


if __name__ == '__main__':
    main()
